global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  # Scrape backend FastAPI metrics
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  # Scrape Node Exporter for host infrastructure metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

